name: Check

on: [ pull_request ]

jobs:
    build:
        name: Check PR

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.8

            -   name: Install Python dependencies
                run: |
                    python -m pip install -U pip wheel
                    python -m pip install -r requirements.txt

            -   name: Validate input
                run: python scripts/check.py

            -   name: Stricht check
                run: |
                    export CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
                    echo $CHANGED_FILES
                    if [ -z "$CHANGED_FILES" ]; then echo "No files available"; elif [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then python scripts/strict_check.py $CHANGED_FILES; fi
