name: Deploy

on:
    push:
        branches:
            - gh-pages

jobs:
    build:
        name: Deploy

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: 3.8

            -   name: Install Python dependencies
                run: |
                    python -m pip install -U pip wheel
                    python -m pip install -r requirements.txt

            -   name: Install xmllint
                run: sudo apt-get install libxml2-utils

            -   name: Validate input
                run: python scripts/check.py $(find sources -type f -name '*.geojson')

            -   name: Create GeoJSON
                run: python scripts/concat_geojson.py $(find sources -type f -name '*.geojson')

            -   name: Create JSON
                run: python scripts/convert_geojson_to_legacyjson.py $(find sources -type f -name '*.geojson')

            -   name: Create XML
                run: python scripts/convert_xml.py sources

            -   name: Validate XML
                run: xmllint --schema scripts/maps.xsd imagery.xml --noout

            -   name: Create deploy folder
                run: |
                    mkdir deploy
                    mv imagery.geojson deploy
                    mv imagery.json deploy
                    mv imagery.xml deploy

            -   name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@3.7.1
                with:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    BRANCH: gh-pages # The branch the action should deploy to.
                    FOLDER: deploy # The folder the action should deploy.
                    CLEAN: false
