name: Check PR

on: [pull_request]

jobs:
  check:
    name: Check PR
    runs-on: [ubuntu-20.04]
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip wheel
          python -m pip install -r requirements.txt

      - name: Basic check
        run: python scripts/check.py sources

      - name: Strict check
        run: |
          export CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          echo $CHANGED_FILES