name: ELI WMS sync

on: [push, pull_request]

jobs:
    build:
        name: WMS_sync

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Python
                uses: actions/setup-python@v2
                with:
                    python-version: '3.8'

            -   name: Install Python dependencies
                run: |
                    python -m pip install --upgrade pip
                    python -m pip install -r requirements-wms.txt

            -   name: Run WMS sync
                run: |
                    python scripts/sync_wms.py sources

            -   name: Create Pull Request
                uses: peter-evans/create-pull-request@v3
                with:
                    commit-message: Sync WMS sources
                    delete-branch: true
                    draft: false
                    title: WMS update
                    body: WMS Sync by scripts/sync_wms.py
